import Head from "next/head";
import { Inter } from "next/font/google";
import Styles from "../styles/Landing.module.scss";
import { Col, Image, Row } from "antd";
import { useRouter } from "next/router";
import Marquee from "react-fast-marquee";
import ImageSlider from "../components/ImgSlider.jsx";
import Lottie from "react-lottie";
import * as animationData from "../public/glyph1.json";
// import * as animationData1 from "../public/Innovation.json";
import * as animationData2 from "../public/datasecurity.json";
import Link from "next/link";
export default function Home() {
  const router = useRouter();

  const BtnClick = () => {
    const onLoginSubmit = async (values) => {
      router.push("/apeal");
    }
  }
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  // const defaultOptions1 = {
  //   loop: true,
  //   autoplay: true,
  //   animationData: animationData1,
  //   rendererSettings: {
  //     preserveAspectRatio: "xMidYMid slice",
  //   },
  // };

  const defaultOptions2 = {
    loop: true,
    autoplay: true,
    animationData: animationData2,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };
  return (
    <>
      <Head>
        <title>SwachhWeb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.container}>
        <div className={Styles.navbar}>
          <Image src="/2img.png" alt="" preview={false} style={{height:"12vh"}}></Image>
          <Row>
            <div className={Styles.registerBtn}>
              {" "}
              <Link href="/login">Admin Login</Link>{" "}
            </div>
            <div className={Styles.loginBtn}>
              <Link href="/login">Super Admin Login</Link>
            </div>
          </Row>
        </div>
        <div className={Styles.hero}>
          <div className={Styles.heroText}>
            &quot;Detect, <span>Restrict</span>, Protect&quot;
            <div className={Styles.heroText2}>
            Experience a safer internet with our content blocking software
            </div>
            <Row style={{ marginTop: "3rem" }}>
              <div className={Styles.registerBtn}>
                {" "}
                <Link href="https://guidelines.india.gov.in/compliance-matrix/#1585239298471-fd39317c-8b66" target="_blank">Compliance standards</Link>{" "}
              </div>
              <div className={Styles.loginBtn}>
                <Link href="/apeal">Unblock Appeal</Link>
              </div>
            </Row>
          </div>
          <div className={Styles.heroImage}>
            <Lottie
              options={defaultOptions}
              height={400}
              width={400}
              style={{ margin: 0 }}
            />
          </div>
        </div>
        <div className={Styles.about}>
          <div className={Styles.aboutCarousel}>
            <ImageSlider />
          </div>
          <div className={Styles.startups}>
            <div className={Styles.aboutStats}>
              <div className={Styles.aboutStatsItem}>
                <div className={Styles.aboutStatsItemNumber}>450M</div>
                <div className={Styles.aboutStatsItemText}>AIU's</div>
              </div>
              <div className={Styles.aboutStatsItem}>
                <div className={Styles.aboutStatsItemNumber}>584</div>
                <div className={Styles.aboutStatsItemText}>ISP's</div>
              </div>
              <div className={Styles.aboutStatsItem}>
                <div className={Styles.aboutStatsItemNumber}>100K</div>
                Blocked Url's
              </div>
            </div>
            <div className={Styles.aboutMarq}>
              <Marquee speed={"80"}>
                <Image src="/logos/1.png" alt="" preview={false}></Image>
                <Image src="/logos/2.png" alt="" preview={false}></Image>
                <Image src="/logos/3.png" alt="" preview={false}></Image>
                <Image src="/logos/4.png" alt="" preview={false}></Image>
                <Image src="/logos/5.png" alt="" preview={false}></Image>
                <Image src="/logos/6.png" alt="" preview={false}></Image>
              </Marquee>
            </div>
          </div>
        </div>
        <div className={Styles.aboutDeets}>
          <div className={Styles.about1}>
            <div>
              <h1
                style={{
                  fontSize: "2rem",
                  marginLeft: "2rem",
                }}
              >
               Cyber Surakshit Bharat
              </h1>
              <h3
                style={{
                  fontSize: "1.4rem",
                  fontWeight: "400",
                  width: "80%",
                  marginLeft: "2rem",
                }}
              >
                An initiative from the Ministry of Electronics and Information Technology (MeitY) that pointed at creating a robust cybersecurity ecosystem in India. This aligns with the government's vision for a 'Digital India'. 
              </h3>
            </div>
            {/* <Lottie
              options={defaultOptions}
              height={400}
              width={400}
              style={{ margin: 0 }}
            /> */}
            <Image src="pm_image.png" style={{paddingRight:"3rem", height:"20rem" , width:"20rem"} } preview={false}>
              
            </Image>
          </div>
          <div className={Styles.about2}>
            <Lottie
              options={defaultOptions2}
              height={300}
              width={500}
              style={{ margin: 0 }}
            />
            <div
              style={{
                width: "40%",
              }}
            >
              <h1
                style={{
                  fontSize: "2rem",
                }}
              >
                 Personal Data Protection Bill
              </h1>
              <h3
                style={{
                  fontSize: "1.4rem",
                  fontWeight: "400",
                  width: "80%",
                }}
              >
               The most important one for Indian citizens is the approval of the Personal Data Protection Bill by the Union Government to protect Indian users from global breaches, which focuses on data localization
              </h3>
            </div>
            {/* give me more content ideas */}
          </div>
        </div>
        <div className={Styles.testimonials}>
          <div className={Styles.testimonialsTitle}>A note from the government</div>
          <div className={Styles.testimonialsCarousel}>
            <div className={Styles.testimonialsCarouselItem}>
              <Image src="/apos.png" alt="" preview={false}></Image>
              <div className={Styles.testimonialsCarouselItemTitle}>
              Never share personal information 
              </div>
              <div className={Styles.testimonialsCarouselItemText}>
              Sharing your personal information with unknown persons on the internet can result in identity theft and other problems. Citizens are advised to not disclose their private information including bank account details on the internet
              </div>
            </div>
            <div className={Styles.testimonialsCarouselItem}>
              <Image src="/apos.png" alt="" preview={false}></Image>
              <div className={Styles.testimonialsCarouselItemTitle}>
              Maintain netiquette while online
              </div>
              <div className={Styles.testimonialsCarouselItemText}>
              Netiquette is an abbreviation of Internet etiquette. It consists of guidelines for sending email, conversing online, and so on. The purpose of netiquette is to help develop an efficient environment for online communication.
              </div>
            </div>
            <div className={Styles.testimonialsCarouselItem}>
              <Image src="" alt="" preview={false}></Image>
              <div className={Styles.testimonialsCarouselItemTitle}>
              Take care with what you share online
              </div>
              <div className={Styles.testimonialsCarouselItemText}>
              Sharing information like OTPs, bank card details and addresses on the internet can be risky. Even in case of a grievance redressal from a company, it is always advisable to share personal details via DMs to the verified social media accounts only.
              </div>
            </div>
          </div>
        </div>
        <div className={Styles.footer}>SwachhWeb</div>
      </div>
    </>
  );
}